### PR TITLE
Character Controller bindings

### PR DESCRIPTION
**Pull request by ashconnell**
This adds the basics for character controllers. I have this working on an internal project and I can probably whip up an example if anyone wants it. I was basically just following the official user guide for character controllers which is super easy to understand anyway:

https://gameworksdocs.nvidia.com/PhysX/4.1/documentation/physxguide/Manual/CharacterControllers.html

@prestomation let me know if there is anything you want changed, including code formatting etc

### CODE REVIEW

**Comment by ashconnell** [comment]
Probably merge the commits together so my initial WIP stuff doesn't stay in the history

**Comment by prestomation** [comment]
Looks great! Did you happen to see how filesize changed before and after these commits?

**Comment by prestomation** [comment]
Looks great! Did you happen to see how filesize changed before and after these commits?

**Comment by ashconnell** [comment]
@prestomation 

```
-rw-rw-rw-  1 ashconnell  staff   142K 17 Jan 16:53 original.physx.release.js
-rw-rw-rw-  1 ashconnell  staff   144K 19 Jan 17:33 physx.release.js
-rw-rw-rw-  1 ashconnell  staff   2.8M 17 Jan 16:53 original.physx.release.wasm
-rw-rw-rw-  1 ashconnell  staff   2.9M 19 Jan 17:33 physx.release.wasm
```

Not too bad! As long as we only bind the API needed then we should be good.

**Pull request merged**
